### ISSUE TITLE
Upgrade to Gatsby 3

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#2447]
Currently we are at Gatsby 2, which holds back our image processing.

By upgrading to Gatsby v3, we can:
- [ ] Upgrade `sharp` and corresponding image packages(`gatsby-plugin-sharp`, `gatsby-transformer-sharp`, `gatsby-image`, etc.)
- [ ] Upgrade to Node version 16(Currently at 15)

Issues that will need to be resolved when we upgrade:
- [ ] Upgrading to v3 will likely break our custom caching mechanism, we'll need to make sure it's working and correct any issues that may arise.

**Comment by shcheklein** [comment]
@julieg18 this is a great summary, thanks! I wonder if we have some ticket related to caching already (cc @rogermparent )?

**Comment by julieg18** [comment]
I couldn't find one, but there are quite a few issues, I could have easily missed one 🤔

**Comment by rogermparent** [comment]
#1063 is an old ticket about image caching that can provide some context, particularly the latest comment from me on there can be considered a call for this Issue (though I think it was still Gatsby 2 then)

**Comment by julieg18** [comment]
> There's been a lot of iterations on those plugins since then, so it may be worth trying an update in a PR to see if the cache behavior improvements also fixed our issue. If we are able to use the latest versions of those plugins, we'll get access to a slew of new features like that greatly improve DX like lazy queries/images and true parallel processing

I attempted to update dvc.org to Gatsby 3 but even with the latest updates to Gatsby and its packages, our caching mechanism still breaks when deploying. Though I'm not sure if its for a different reason than last time we attempted this.

Error Message in Failed Build Script:
<details>

```
success Building HTML renderer - 20.597s
error Page data from page-data.json for the failed page "/doc": {
  "componentChunkName": "component---src-templates-doc-tsx",
  "path": "/doc",
  "result": {
    "data": {
      "page": {
        "title": null,
        "description": null,
        "htmlAst": {
          "type": "root",
          "children": [
            {
              "type": "element",
              "tagName": "h1",
              "properties": {
                "id": "dvc-documentation",
                "style": "position:relative;"
              },
              "children": [
                {
                  "type": "text",
                  "value": "DVC Documentation"
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "#dvc-documentation",
                    "ariaLabel": "dvc documentation permalink",
                    "className": [
                      "anchor",
                      "after"
                    ]
                  },
                  "children": [
                    {
                      "type": "element",
                      "tagName": "svg",
                      "properties": {
                        "ariaHidden": "true",
                        "focusable": "false",
                        "height": "16",
                        "version": "1.1",
                        "viewBox": "0 0 16 16",
                        "width": "16"
                      },
                      "children": [
                        {
                          "type": "element",
                          "tagName": "path",
                          "properties": {
                            "fillRule": "evenodd",
                            "d": "M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2...."
                          },
                          "children": []
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "p",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "Data Version Control, or DVC, is a data and ML\n"
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "/doc/user-guide/experiment-management"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "experiment management"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " tool that takes\nadvantage of the existing engineering toolset that you're already familiar with\n(Git, CI/CD, etc.)."
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "cards",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "\n  "
                },
                {
                  "type": "element",
                  "tagName": "card",
                  "properties": {
                    "href": "/doc/start",
                    "heading": "Get Started"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "\n    A step-by-step introduction into basic DVC features\n  "
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\n  "
                },
                {
                  "type": "element",
                  "tagName": "card",
                  "properties": {
                    "href": "/doc/user-guide",
                    "heading": "User Guide"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "\n    Study the detailed inner-workings of DVC in its user guide.\n  "
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\n  "
                },
                {
                  "type": "element",
                  "tagName": "card",
                  "properties": {
                    "href": "/doc/use-cases",
                    "heading": "Use Cases"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "\n    Non-exhaustive list of scenarios DVC can help with\n  "
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\n  "
                },
                {
                  "type": "element",
                  "tagName": "card",
                  "properties": {
                    "href": "/doc/command-reference",
                    "heading": "Command Reference"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "\n    See all of DVC's commands.\n  "
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\n"
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "p",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "✅ Please join our "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "/community"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "community"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " or use the "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "/support"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "support"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\nchannels if you have any questions or need specific help. We are very responsive\n⚡."
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "p",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "✅ Check out our "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "https://github.com/iterative/dvc",
                    "target": "_blank",
                    "rel": [
                      "nofollow",
                      "noopener",
                      "noreferrer"
                    ]
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "GitHub repository"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " and give\nus a ⭐ if you like the project!"
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "p",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "✅ Contribute to DVC "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "https://github.com/iterative/dvc",
                    "target": "_blank",
                    "rel": [
                      "nofollow",
                      "noopener",
                      "noreferrer"
                    ]
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "on GitHub"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " or help us\nimprove this "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "https://github.com/iterative/dvc.org",
                    "target": "_blank",
                    "rel": [
                      "nofollow",
                      "noopener",
                      "noreferrer"
                    ]
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "documentation"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " 🙏."
                }
              ]
            }
          ],
          "data": {
            "quirksMode": false
          }
        }
      }
    },
    "pageContext": {
      "id": "5cd08ce1-ee69-5c83-9f79-db0481e3f50d",
      "slug": "/doc",
      "isDocs": true,
      "headings": []
    }
  },
  "staticQueryHashes": []
}
       failed Building static HTML for pages - 1.607s
error Building static HTML failed for path "/doc"
       
         75 |     return context[query].data
         76 |   } else {
       > 77 |     throw new Error(
            |           ^
         78 |       `The result of this StaticQuery could not be fetched.\n\n` +
         79 |         `This is likely a bug in Gatsby and if refreshing the page does not fix it, ` +
         80 |         `please open an issue in https://github.com/gatsbyjs/gatsby/issues`
       
       
         WebpackError: The result of this StaticQuery could not be fetched.
         
         - gatsby-browser-entry.js:77 
           website/.cache/gatsby-browser-entry.js:77:11
         
         - siteMeta.ts:13 
         [0m  website/src/queries/siteMeta.ts:13:21
         
         - index.tsx:18 
           website/src/components/Page/DefaultSEO/index.tsx:18:31
         
         - defineProperty.js:8 
           [website]/[@babel]/runtime/helpers/defineProperty.js:8:6
         
         - defineProperty.js:11 
           [website]/[@babel]/runtime/helpers/defineProperty.js:11:1
         
         - defineProperty.js:16 
           [website]/[@babel]/runtime/helpers/defineProperty.js:16:1
         
         - defineProperty.js:16 
           [website]/[@babel]/runtime/helpers/defineProperty.js:16:1
         
         - static-entry.js:286 
           website/.cache/static-entry.js:286:22
         
         - history.js:157 
           [website]/[@gatsbyjs]/reach-router/es/lib/history.js:157:1
         
       
       not finished Caching HTML renderer compilation - 1.691s
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------------------------
The first Gatsby build attempt failed!
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:707:11)
    at execSync (node:child_process:744:15)
    at run (/tmp/build_e768bb43/scripts/deploy-with-s3.js:76:3)
    at main (/tmp/build_e768bb43/scripts/deploy-with-s3.js:100:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1936,
  stdout: null,
  stderr: null
}
```

</details>


Entire Failed Build Script:

<details>

```
       ...yarn run v1.22.11
       $ ./scripts/deploy-with-s3.js
       {
         AWS_REGION: 'us-east-2',
         HEROKU_APP_NAME: 'dvc-org-test-caching-vpcsge9cu',
         s3Bucket: 'dvc-public',
         s3Prefix: 'dvc-org-pulls/dvc-org-test-caching-vpcsge9cu',
         hasCreds: true
       }
       Downloading "public" from s3://dvc-public/dvc-org-pulls/dvc-org-test-caching-vpcsge9cu/
       Downloading ".cache" from s3://dvc-public/dvc-org-pulls/dvc-org-test-caching-vpcsge9cu-cache/
       "public" downloaded in: 41.715s
       ".cache" downloaded in: 42.892s
       $ gatsby build
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
       success open and validate gatsby-configs, load plugins - 2.690s
       success onPreInit - 0.067s
       success initialize cache - 0.015s
       success copy gatsby files - 0.092s
       success Compiling Gatsby Functions - 0.359s
       success onPreBootstrap - 0.371s
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
       success createSchemaCustomization - 0.458s
       success Checking for changed pages - 0.001s
       success source and transform nodes - 6.425s
       success building schema - 1.810s
       success createPages - 0.262s
warning Non-deterministic routing danger: Attempting to create page: "/404/", but page "/404" already exists
This could lead to non-deterministic routing behavior
warning Non-deterministic routing danger: Attempting to create page: "/community/", but page "/community" already exists
This could lead to non-deterministic routing behavior
warning Non-deterministic routing danger: Attempting to create page: "/enterprise/", but page "/enterprise" already exists
This could lead to non-deterministic routing behavior
warning Non-deterministic routing danger: Attempting to create page: "/features/", but page "/features" already exists
This could lead to non-deterministic routing behavior
warning Non-deterministic routing danger: Attempting to create page: "/subscriber-thank-you/", but page "/subscriber-thank-you" already exists
This could lead to non-deterministic routing behavior
warning Non-deterministic routing danger: Attempting to create page: "/support/", but page "/support" already exists
This could lead to non-deterministic routing behavior
warning Non-deterministic routing danger: Attempting to create page: "/doc/user-guide/glossary/", but page "/doc/user-guide/glossary" already exists
This could lead to non-deterministic routing behavior
       success createPagesStatefully - 0.185s
       info Total nodes: 2082, SitePage nodes: 368 (use --verbose for breakdown)
       success Checking for changed pages - 0.014s
       success Cleaning up stale page-data - 0.046s
       success update schema - 0.266s
       success onPreExtractQueries - 0.000s
       success extract queries from components - 3.591s
       success write out redirect data - 0.003s
       success Build manifest and related icons - 0.086s
       success onPostBootstrap - 0.089s
       info bootstrap finished - 19.691s
       success run static queries - 0.005s - 1/1 191.98/s
warning Query takes too long:
File path: /tmp/build_e768bb43/src/templates/blog-home.tsx
URL path: /blog
Context: {
    "isBlog": true,
    "limit": 7,
    "pageInfo": {
        "currentPage": 1,
        "nextPage": "/blog/page/2"
    },
    "skip": 0
}
warning Query takes too long:
File path: /tmp/build_e768bb43/src/templates/blog-home.tsx
URL path: /blog/page/2
Context: {
    "isBlog": true,
    "limit": 9,
    "pageInfo": {
        "currentPage": 2,
        "nextPage": "/blog/page/3",
        "previousPage": "/blog"
    },
    "skip": 7
}
warning Query takes too long:
File path: /tmp/build_e768bb43/src/templates/blog-home.tsx
URL path: /blog/page/3
Context: {
    "isBlog": true,
    "limit": 9,
    "pageInfo": {
        "currentPage": 3,
        "nextPage": "/blog/page/4",
        "previousPage": "/blog/page/2"
    },
    "skip": 16
}
warning Query takes too long:
File path: /tmp/build_e768bb43/src/templates/blog-home.tsx
URL path: /blog/page/4
Context: {
    "isBlog": true,
    "limit": 9,
    "pageInfo": {
        "currentPage": 4,
        "nextPage": "/blog/page/5",
        "previousPage": "/blog/page/3"
    },
    "skip": 25
}
warning Query takes too long:
File path: /tmp/build_e768bb43/src/templates/blog-home.tsx
URL path: /blog/page/5
Context: {
    "isBlog": true,
    "limit": 9,
    "pageInfo": {
        "currentPage": 5,
        "nextPage": "/blog/page/6",
        "previousPage": "/blog/page/4"
    },
    "skip": 34
}
warning Query takes too long:
File path: /tmp/build_e768bb43/src/templates/blog-home.tsx
URL path: /blog/page/6
Context: {
    "isBlog": true,
    "limit": 9,
    "pageInfo": {
        "currentPage": 6,
        "nextPage": "/blog/page/7",
        "previousPage": "/blog/page/5"
    },
    "skip": 43
}
warning Query takes too long:
File path: /tmp/build_e768bb43/src/templates/blog-home.tsx
URL path: /blog/page/7
Context: {
    "isBlog": true,
    "limit": 9,
    "pageInfo": {
        "currentPage": 7,
        "nextPage": "/blog/page/8",
        "previousPage": "/blog/page/6"
    },
    "skip": 52
}
warning Query takes too long:
File path: /tmp/build_e768bb43/src/templates/blog-home.tsx
URL path: /blog/page/8
Context: {
    "isBlog": true,
    "limit": 9,
    "pageInfo": {
        "currentPage": 8,
        "nextPage": "/blog/page/9",
        "previousPage": "/blog/page/7"
    },
    "skip": 61
}
       success run page queries - 126.965s - 361/361 2.84/s
       success write out requires - 0.013s
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
       success Building production JavaScript and CSS bundles - 105.819s
       success Rewriting compilation hashes - 0.018s
       success Writing page-data.json files to public directory - 0.947s - 368/368 388.80/s
       success Caching JavaScript and CSS webpack compilation - 46.805s
       success Building HTML renderer - 20.597s
error Page data from page-data.json for the failed page "/doc": {
  "componentChunkName": "component---src-templates-doc-tsx",
  "path": "/doc",
  "result": {
    "data": {
      "page": {
        "title": null,
        "description": null,
        "htmlAst": {
          "type": "root",
          "children": [
            {
              "type": "element",
              "tagName": "h1",
              "properties": {
                "id": "dvc-documentation",
                "style": "position:relative;"
              },
              "children": [
                {
                  "type": "text",
                  "value": "DVC Documentation"
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "#dvc-documentation",
                    "ariaLabel": "dvc documentation permalink",
                    "className": [
                      "anchor",
                      "after"
                    ]
                  },
                  "children": [
                    {
                      "type": "element",
                      "tagName": "svg",
                      "properties": {
                        "ariaHidden": "true",
                        "focusable": "false",
                        "height": "16",
                        "version": "1.1",
                        "viewBox": "0 0 16 16",
                        "width": "16"
                      },
                      "children": [
                        {
                          "type": "element",
                          "tagName": "path",
                          "properties": {
                            "fillRule": "evenodd",
                            "d": "M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2...."
                          },
                          "children": []
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "p",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "Data Version Control, or DVC, is a data and ML\n"
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "/doc/user-guide/experiment-management"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "experiment management"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " tool that takes\nadvantage of the existing engineering toolset that you're already familiar with\n(Git, CI/CD, etc.)."
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "cards",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "\n  "
                },
                {
                  "type": "element",
                  "tagName": "card",
                  "properties": {
                    "href": "/doc/start",
                    "heading": "Get Started"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "\n    A step-by-step introduction into basic DVC features\n  "
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\n  "
                },
                {
                  "type": "element",
                  "tagName": "card",
                  "properties": {
                    "href": "/doc/user-guide",
                    "heading": "User Guide"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "\n    Study the detailed inner-workings of DVC in its user guide.\n  "
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\n  "
                },
                {
                  "type": "element",
                  "tagName": "card",
                  "properties": {
                    "href": "/doc/use-cases",
                    "heading": "Use Cases"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "\n    Non-exhaustive list of scenarios DVC can help with\n  "
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\n  "
                },
                {
                  "type": "element",
                  "tagName": "card",
                  "properties": {
                    "href": "/doc/command-reference",
                    "heading": "Command Reference"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "\n    See all of DVC's commands.\n  "
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\n"
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "p",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "✅ Please join our "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "/community"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "community"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " or use the "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "/support"
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "support"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": "\nchannels if you have any questions or need specific help. We are very responsive\n⚡."
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "p",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "✅ Check out our "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "https://github.com/iterative/dvc",
                    "target": "_blank",
                    "rel": [
                      "nofollow",
                      "noopener",
                      "noreferrer"
                    ]
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "GitHub repository"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " and give\nus a ⭐ if you like the project!"
                }
              ]
            },
            {
              "type": "text",
              "value": "\n"
            },
            {
              "type": "element",
              "tagName": "p",
              "properties": {},
              "children": [
                {
                  "type": "text",
                  "value": "✅ Contribute to DVC "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "https://github.com/iterative/dvc",
                    "target": "_blank",
                    "rel": [
                      "nofollow",
                      "noopener",
                      "noreferrer"
                    ]
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "on GitHub"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " or help us\nimprove this "
                },
                {
                  "type": "element",
                  "tagName": "a",
                  "properties": {
                    "href": "https://github.com/iterative/dvc.org",
                    "target": "_blank",
                    "rel": [
                      "nofollow",
                      "noopener",
                      "noreferrer"
                    ]
                  },
                  "children": [
                    {
                      "type": "text",
                      "value": "documentation"
                    }
                  ]
                },
                {
                  "type": "text",
                  "value": " 🙏."
                }
              ]
            }
          ],
          "data": {
            "quirksMode": false
          }
        }
      }
    },
    "pageContext": {
      "id": "5cd08ce1-ee69-5c83-9f79-db0481e3f50d",
      "slug": "/doc",
      "isDocs": true,
      "headings": []
    }
  },
  "staticQueryHashes": []
}
       failed Building static HTML for pages - 1.607s
error Building static HTML failed for path "/doc"
       
         75 |     return context[query].data
         76 |   } else {
       > 77 |     throw new Error(
            |           ^
         78 |       `The result of this StaticQuery could not be fetched.\n\n` +
         79 |         `This is likely a bug in Gatsby and if refreshing the page does not fix it, ` +
         80 |         `please open an issue in https://github.com/gatsbyjs/gatsby/issues`
       
       
         WebpackError: The result of this StaticQuery could not be fetched.
         
         - gatsby-browser-entry.js:77 
           website/.cache/gatsby-browser-entry.js:77:11
         
         - siteMeta.ts:13 
         [0m  website/src/queries/siteMeta.ts:13:21
         
         - index.tsx:18 
           website/src/components/Page/DefaultSEO/index.tsx:18:31
         
         - defineProperty.js:8 
           [website]/[@babel]/runtime/helpers/defineProperty.js:8:6
         
         - defineProperty.js:11 
           [website]/[@babel]/runtime/helpers/defineProperty.js:11:1
         
         - defineProperty.js:16 
           [website]/[@babel]/runtime/helpers/defineProperty.js:16:1
         
         - defineProperty.js:16 
           [website]/[@babel]/runtime/helpers/defineProperty.js:16:1
         
         - static-entry.js:286 
           website/.cache/static-entry.js:286:22
         
         - history.js:157 
           [website]/[@gatsbyjs]/reach-router/es/lib/history.js:157:1
         
     
       not finished Caching HTML renderer compilation - 1.691s
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------------------------
The first Gatsby build attempt failed!
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:707:11)
    at execSync (node:child_process:744:15)
    at run (/tmp/build_e768bb43/scripts/deploy-with-s3.js:76:3)
    at main (/tmp/build_e768bb43/scripts/deploy-with-s3.js:100:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1936,
  stdout: null,
  stderr: null
}
Retrying with a cleared cache:
       $ gatsby build...
```

</details>

**Comment by rogermparent** [comment]
> our caching mechanism still breaks when deploying. Though I'm not sure if its for a different reason than last time we attempted this.

When I mention the caching mechanism failing, I'm specifically referring to how after all errors are squashed and builds are successful, cache is invalidated on every build. Builds succeed, but take over twice the amount of time because all images are re-processed after each build.

There were regular errors like that one on the first attempt, but even after solving all of those the caching mysteriously didn't work despite us using a hand-rolled version of effectively the same cache preservation method other services like Netlify successfully do (upload `public` and `.cache` after build, download before next build).
